services:
  postgres:
    image: postgres:16
    container_name: cinema-postgres
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: cinema123
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - cinema_pgdata:/var/lib/postgresql/data

volumes:
  cinema_pgdata:
